### ISSUE TITLE
Unable to run a training with the pl_training script

### ISSUE THREAD

**Issue by laleye** [allenai/scirepeval#44]
**To reproduce**

- Download datasets manually: wget https://ai2-s2-research-public.s3.us-west-2.amazonaws.com/scirepeval/train/fos/val.jsonl -P ../../validation/
- Below the config
```
[
 {
     "name": "fos",
     "type": "classification",
     "multi_label": true,
     "data_files":
     {
         "train": "./Datasets/scirepeval/train/train.jsonl",
         "dev": "./Datasets/scirepeval/validation/val.jsonl"
     },
     "labels": "sample_data/fos_labels.txt",
     "labels_field": "labels_text",
     "ctrl_token": "[CLF]",
     "sample_size":
     {
         "train": 1,
         "dev": 1
     }
 }
]
```

- Command to run the training `python pl_training.py --tasks-config sample_data/config.json allenai/scibert_scivocab_uncased  fos --batch-size 32 --gpu 1`

**Here is the error I obtained. Probably an error from datasets I downloaded ?**

```
ValueError: Caught ValueError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/_utils/fetch.py", line 32, in fetch
    data.append(next(self.dataset_iter))
  File "/content/drive/Datasets/scirepeval/scirepeval/training/mtl_datasets.py", line 241, in iter_slice
    curr_batch[idx] = next(curr_iter)
  File "/content/drive/Datasets/scirepeval/scirepeval/training/strategies.py", line 45, in get_batch_iter
    x = next(it)
  File "/content/drive/Datasets/scirepeval/scirepeval/training/mtl_datasets.py", line 144, in sub_sample
    X, y = zip(*[(d, tuple(d[self.label_field])) for d in json_parse])
ValueError: not enough values to unpack (expected 2, got 0)
```

Any help please.

**Comment by amanpreet692** [comment]
Hello, 
I looked into it but am not able to re-produce the issue even on re-downloading the dataset.
From the posted error it looks like the json datafile wasn't read properly .
Can you help with answers to the following questions, it may help in the investigation:
i) Does the validation sanity step succeed? I assume this error comes before training starts
ii) Any particular reason the sample size is set as 1 in config.json?
iii) The error stack above points to line 144 for the error... 
```File "/content/drive/Datasets/scirepeval/scirepeval/training/mtl_datasets.py", line 144, in sub_sample
    X, y = zip(*[(d, tuple(d[self.label_field])) for d in json_parse])```

But in the main branch code his particular code is at line 136. Have some changes be made to the mtl_datasets.py script?
Could you please share the custom script?
iv) Complete error stack 

Please also let us know if anything else is different in the environment that might be helpful.
Thanks!

**Comment by laleye** [comment]
@amanpreet692 Thank you for your reply.
I put back the basic config and I still have the same error. Here is my config and installed packages.

**config.json**
```

[
 {
     "name": "fos",
     "type": "classification",
     "multi_label": true,
     "data_files":
     {
         "train": "/content/drive/Datasets/scirepeval/train/train.jsonl",
         "dev": "/content/drive/Datasets/scirepeval/validation/val.jsonl"
     },
     "labels": "sample_data/fos_labels.txt",
     "labels_field": "labels_text",
     "ctrl_token": "[CLF]",
     "sample_size":
     {
         "train": 600000,
         "dev": 40000
     }
 }
]
```

**packages**

`!pip install pytorch-lightning==1.7.2 transformers==4.21.1 scikit-multilearn==0.2.0 adapter-transformers==3.0.1 datasets fairseq zipp==3.8.1`

**Error encountered**

Sanity Checking: 0it [00:00, ?it/s]/usr/local/lib/python3.9/dist-packages/torch/utils/data/dataloader.py:561: UserWarning: This DataLoader will create 12 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
Traceback (most recent call last):
  File "/content/drive/Datasets/scirepeval/scirepeval/training/pl_training.py", line 324, in <module>
    trainer.fit(model)
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/trainer.py", line 648, in _call_and_handle_interrupt
    return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 93, in launch
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/trainer.py", line 737, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/trainer.py", line 1168, in _run
    results = self._run_stage()
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/trainer.py", line 1254, in _run_stage
    return self._run_train()
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/trainer.py", line 1276, in _run_train
    self._run_sanity_check()
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/trainer.py", line 1345, in _run_sanity_check
    val_loop.run()
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 155, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 127, in advance
    batch = next(data_fetcher)
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/utilities/fetching.py", line 185, in __next__
    return self.fetching_function()
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/utilities/fetching.py", line 257, in fetching_function
    self._fetch_next_batch(self.dataloader_iter)
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/utilities/fetching.py", line 278, in _fetch_next_batch
    batch = next(iterator)
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/dataloader.py", line 634, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/dataloader.py", line 1326, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.9/dist-packages/torch/_utils.py", line 644, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/_utils/fetch.py", line 32, in fetch
    data.append(next(self.dataset_iter))
  File "/content/drive/Datasets/scirepeval/scirepeval/training/mtl_datasets.py", line 230, in iter_slice
    curr_batch[idx] = next(curr_iter)
  File "/content/drive/Datasets/scirepeval/scirepeval/training/strategies.py", line 44, in get_batch_iter
    x = next(it)
  File "/content/drive/Datasets/scirepeval/scirepeval/training/mtl_datasets.py", line 136, in sub_sample
    X, y = zip(*[(d, tuple(d[self.label_field])) for d in json_parse])
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by amanpreet692** [comment]
Hello again, thanks for providing additional info.
It was helpful, given the context I tried replicating the issue on Google Colab and succeeded :)
The issue here seems to stem from the version of the datasets library. It looks like the v2.8.0 was updated for using Iterable Datasets in Pytorch DataLoader which are incompatible with our code.
The reason for the error above is that IterableDatasets should be replicated in PyTorch if multiple workers are configured in the DataLoader which is the case here:
https://github.com/allenai/scirepeval/blob/8f00aa9871bb0b41c29e60f3dafcff9043b9799c/training/pl_training.py#L239

Somehow this breaks with the newer version and the dataset is exhausted by one of the workers resulting in the other throwing an error.

To solve this, you can just use the version for datasets we specify in https://github.com/allenai/scirepeval/blob/main/requirements.txt as
```
pip install -U datasets==2.5.2
```
